### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by RDIL** [chrissimpkins/md2rst#1]
Can you please add windows support?  Thanks!

**Comment by chrissimpkins** [comment]
Is pandoc available on Win, and if so, what path is it stored on?

**Comment by RDIL** [comment]
let me check

**Comment by chrissimpkins** [comment]
sorry it is pandoc based... no fanciness implemented here.

**Comment by RDIL** [comment]
No problem, just couldn't find the directory.
